### PR TITLE
some css fixes

### PR DESCRIPTION
**Pull request by MythicalMayhem**
added flex box and removed unnecessary margins, 
also added link to project author in the </footer>

### CODE REVIEW

**Comment by a3ryk** [comment]
Please share the recording/screenshots of the changes working results.

**Review by a3ryk — CHANGES_REQUESTED** [review]
Please remove the package-lock.json

**Comment by MythicalMayhem** [comment]
before
image
after
image

example usage of CSS flexbox  and removal of unnecessary margins 
image

**Comment by MythicalMayhem** [comment]
> Please remove the package-lock.json

done

**Pull request closed without merging**
